# Generated by Django 4.2.7 on 2023-11-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopri', '0004_course_alter_good_options_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
